spring:
 port: 10000
 application:
        name: "keycloak-app"
 security:
         oauth2:
             resourceServer:
                 jwt:
                   issuer-uri: http://localhost:9090/realms/Test-auth

keycloakAdmin :
  app1:
    realm: "realm"
    clientId: "clientId"
    clientSecret: "clientSecret"
    serverUrl: "http:localhost:9000"





                  

